Lobby create connect
KhalilovJ/Crossing-the-Rubicon pull request #13
Opened 2024-06-07 21:10 UTC by zahmatiyusif

2024-06-08 09:14 UTC, malishov commented on src/main/java/az/evilcastle/crossingtherubicon/controller/GameSessionController.java
> +       return service.createGameSession(dto,test);
dto -> createGameSession
test -> player

2024-06-08 09:20 UTC, malishov commented on src/main/java/az/evilcastle/crossingtherubicon/controller/GameSessionController.java
> +       return service.createGameSession(dto,test);
2 dto bir requestde ? 
playeri path-a ve ya request parama chixartmaq olar
player-in id-sini misal uchun gondermek

2024-06-08 09:22 UTC, malishov commented on src/main/java/az/evilcastle/crossingtherubicon/service/GameSessionService.java
> +        GameSessionEntity session = GameSessionEntity.builder()
mapstruct ile bunu yazmaqa cehd eledin ?

2024-06-08 09:23 UTC, malishov commented on src/main/java/az/evilcastle/crossingtherubicon/service/GameSessionService.java
> +                .orElseThrow(()->new LobbyIsNotFound("Lobby is not found"));
Session or Lobby ? adlar artiq meni chashdirdi

2024-06-08 09:24 UTC, KhalilovJ commented on src/main/java/az/evilcastle/crossingtherubicon/controller/GameSessionController.java
> +       return service.createGameSession(dto,test);
Request dto etməyi təkıif edirəm, hamısı da içində olsun

2024-06-08 09:25 UTC, malishov commented on src/main/java/az/evilcastle/crossingtherubicon/service/GameSessionService.java
> +        if (Objects.equals(connect.password(), lobby.getPassword())){
if else, if else
temiz gorsenmir
Tovsiye ederdim burani normal veziyyete getirmek

2024-06-08 09:25 UTC, malishov commented on src/main/java/az/evilcastle/crossingtherubicon/service/WebSocketHandlerService.java
> +                WSCreateLobbyMessage ws = (WSCreateLobbyMessage) message;
bu zirraamni ayrica private metoda chixarmaq ollar 
case CREATE_LOBBY -> createLobbyMethod();

2024-06-08 09:26 UTC, malishov commented on src/main/java/az/evilcastle/crossingtherubicon/service/WebSocketHandlerService.java
> +                WSCreateLobbyMessage ws = (WSCreateLobbyMessage) message;
same problem here

2024-06-08 09:29 UTC, malishov commented on src/main/java/az/evilcastle/crossingtherubicon/model/dto/gamesession/GameSessionDto.java
> +        String id,
UUIDdini burda String-e deyishdik, lakin sonra entity yaradanda UUID.randomUUID().toString() istifade  olunur. Why ?

2024-06-08 09:30 UTC, KhalilovJ commented on src/main/java/az/evilcastle/crossingtherubicon/service/GameSessionService.java
> +                .orElseThrow(()->new LobbyIsNotFound("Lobby is not found"));
lobby*

2024-06-08 11:12 UTC, malishov commented on src/main/java/az/evilcastle/crossingtherubicon/controller/GameSessionController.java
> +       return service.createGameSession(dto,test);
onda bidene request ichinde CreateGameSessionDto
digerinde connectionToGameSession ve etc. ? ve ya bidene interface chixatmaq ?
genede qayidiram ki o fikire, requestleri chetinleshdiririk

2024-06-08 11:42 UTC, KhalilovJ commented on src/main/java/az/evilcastle/crossingtherubicon/model/dto/gamesession/GameSessionDto.java
> +        String id,
random string lazimdir, uuid təkrarlanmayan, həm uuid həm də string kimi istifadə oluna bilən bir klassdır

2024-06-10 17:27 UTC, malishov commented on src/main/java/az/evilcastle/crossingtherubicon/service/WebSocketHandlerService.java
> +        PlayerDto connector = new PlayerDto("iloveniggas",message.getWebsocketId());
ala bu nedi ? :D

2024-06-10 19:32 UTC, KhalilovJ requested changes
Please add WebsocketLobbyMapping collection in mongo

2024-06-12 20:37 UTC, merged